# Generated by Django 4.1.3 on 2022-11-19 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_alter_follow_followers_alter_follow_followings_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='followers',
            new_name='follower',
        ),
        migrations.RenameField(
            model_name='follow',
            old_name='followings',
            new_name='following',
        ),
    ]
